SET NAMES utf8mb4;

ALTER TABLE schema_migration_history
  MODIFY COLUMN version VARCHAR(128) NOT NULL COMMENT '迁移版本',
  MODIFY COLUMN checksum CHAR(64) NOT NULL COMMENT '校验值（SHA256）',
  MODIFY COLUMN description VARCHAR(255) NOT NULL COMMENT '迁移说明',
  MODIFY COLUMN applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '应用时间',
  COMMENT = '数据库迁移历史表';

ALTER TABLE sys_user
  MODIFY COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '用户角色',
  MODIFY COLUMN token_version INT NOT NULL DEFAULT 0 COMMENT '令牌版本号';

ALTER TABLE pricing_task
  MODIFY COLUMN task_status VARCHAR(20) NOT NULL DEFAULT 'QUEUED' COMMENT '任务状态',
  MODIFY COLUMN requested_by_user_id BIGINT NULL COMMENT '发起用户ID',
  MODIFY COLUMN trace_id VARCHAR(64) NULL COMMENT '链路追踪ID',
  MODIFY COLUMN idempotency_key VARCHAR(128) NULL COMMENT '幂等键',
  MODIFY COLUMN retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  MODIFY COLUMN failure_reason VARCHAR(255) NULL COMMENT '失败原因',
  MODIFY COLUMN started_at DATETIME NULL COMMENT '开始时间',
  MODIFY COLUMN completed_at DATETIME NULL COMMENT '完成时间',
  MODIFY COLUMN strategy_goal VARCHAR(50) NOT NULL DEFAULT 'MAX_PROFIT' COMMENT '策略目标',
  MODIFY COLUMN constraint_text VARCHAR(1000) NULL COMMENT '约束条件文本',
  MODIFY COLUMN llm_api_key_enc VARCHAR(512) DEFAULT NULL COMMENT 'Fernet 加密的用户 API Key（重试用）',
  MODIFY COLUMN llm_base_url VARCHAR(255) DEFAULT NULL COMMENT '用户 LLM Base URL',
  MODIFY COLUMN llm_model VARCHAR(100) DEFAULT NULL COMMENT '用户 LLM 模型名称';

ALTER TABLE pricing_result
  MODIFY COLUMN review_required TINYINT NOT NULL DEFAULT 1 COMMENT '是否需要人工审核',
  MODIFY COLUMN applied_previous_price DECIMAL(10,2) NULL COMMENT '应用前价格',
  MODIFY COLUMN applied_at DATETIME NULL COMMENT '应用时间',
  MODIFY COLUMN applied_by_user_id BIGINT NULL COMMENT '应用操作人ID';

ALTER TABLE auth_refresh_session
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '刷新会话ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN token_hash CHAR(64) NOT NULL COMMENT '刷新令牌哈希',
  MODIFY COLUMN expires_at DATETIME NOT NULL COMMENT '过期时间',
  MODIFY COLUMN revoked_at DATETIME NULL COMMENT '撤销时间',
  MODIFY COLUMN last_used_at DATETIME NULL COMMENT '最后使用时间',
  MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT '客户端IP',
  MODIFY COLUMN user_agent VARCHAR(255) NULL COMMENT '客户端标识',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '刷新令牌会话表';

ALTER TABLE login_audit_log
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '登录审计ID',
  MODIFY COLUMN user_id BIGINT NULL COMMENT '用户ID',
  MODIFY COLUMN username VARCHAR(50) NULL COMMENT '登录用户名',
  MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT '客户端IP',
  MODIFY COLUMN user_agent VARCHAR(255) NULL COMMENT '客户端标识',
  MODIFY COLUMN login_status VARCHAR(20) NOT NULL COMMENT '登录结果状态',
  MODIFY COLUMN failure_reason VARCHAR(255) NULL COMMENT '失败原因',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  COMMENT = '登录审计日志表';

ALTER TABLE user_llm_config
  MODIFY COLUMN llm_api_key_enc VARCHAR(512) NOT NULL COMMENT 'AES-256-GCM 加密的 API Key',
  MODIFY COLUMN llm_base_url VARCHAR(255) NOT NULL COMMENT 'LLM API Base URL',
  MODIFY COLUMN llm_model VARCHAR(100) NOT NULL COMMENT '模型名称',
  COMMENT = '用户LLM配置';
