SET NAMES utf8mb4;

ALTER TABLE pricing_batch
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '批量定价批次ID',
  MODIFY COLUMN batch_code VARCHAR(50) NOT NULL COMMENT '批次编号',
  MODIFY COLUMN requested_by_user_id BIGINT NOT NULL COMMENT '发起用户ID',
  MODIFY COLUMN strategy_goal VARCHAR(50) NOT NULL COMMENT '定价策略目标',
  MODIFY COLUMN constraint_text VARCHAR(1000) DEFAULT NULL COMMENT '定价约束条件文本',
  MODIFY COLUMN total_count INT NOT NULL DEFAULT 0 COMMENT '批次商品总数',
  MODIFY COLUMN completed_count INT NOT NULL DEFAULT 0 COMMENT '已完成任务数',
  MODIFY COLUMN manual_review_count INT NOT NULL DEFAULT 0 COMMENT '待人工审核任务数',
  MODIFY COLUMN failed_count INT NOT NULL DEFAULT 0 COMMENT '失败商品数',
  MODIFY COLUMN cancelled_count INT NOT NULL DEFAULT 0 COMMENT '已取消任务数',
  MODIFY COLUMN batch_status VARCHAR(20) NOT NULL DEFAULT 'RUNNING' COMMENT '批次状态',
  MODIFY COLUMN finalized_at DATETIME DEFAULT NULL COMMENT '批次首次结束时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '批量定价汇总表';

ALTER TABLE pricing_batch_item
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '批量定价明细ID',
  MODIFY COLUMN batch_id BIGINT NOT NULL COMMENT '批次ID',
  MODIFY COLUMN product_id BIGINT NOT NULL COMMENT '商品ID',
  MODIFY COLUMN item_order INT NOT NULL COMMENT '批次内显示顺序',
  MODIFY COLUMN task_id BIGINT DEFAULT NULL COMMENT '关联定价任务ID',
  MODIFY COLUMN item_status VARCHAR(20) NOT NULL DEFAULT 'TASK_LINKED' COMMENT '明细创建状态',
  MODIFY COLUMN error_message VARCHAR(255) DEFAULT NULL COMMENT '明细级创建失败原因',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '批量定价明细表';
